type Country = {
  name: string;
  twoLetterCode: string;
  threeLetterCode: string;
  threeDigitCode: string;
};

export const countries: Country[] = [
  {
    name: 'Afghanistan',
    twoLetterCode: 'AF',
    threeLetterCode: 'AFG',
    threeDigitCode: '004',
  },
  {
    name: 'Aland Islands',
    twoLetterCode: 'AX',
    threeLetterCode: 'ALA',
    threeDigitCode: '248',
  },
  {
    name: 'Albania',
    twoLetterCode: 'AL',
    threeLetterCode: 'ALB',
    threeDigitCode: '008',
  },
  {
    name: 'Algeria',
    twoLetterCode: 'DZ',
    threeLetterCode: 'DZA',
    threeDigitCode: '012',
  },
  {
    name: 'American Samoa',
    twoLetterCode: 'AS',
    threeLetterCode: 'ASM',
    threeDigitCode: '016',
  },
  {
    name: 'Andorra',
    twoLetterCode: 'AD',
    threeLetterCode: 'AND',
    threeDigitCode: '020',
  },
  {
    name: 'Angola',
    twoLetterCode: 'AO',
    threeLetterCode: 'AGO',
    threeDigitCode: '024',
  },
  {
    name: 'Anguilla',
    twoLetterCode: 'AI',
    threeLetterCode: 'AIA',
    threeDigitCode: '660',
  },
  {
    name: 'Antarctica ',
    twoLetterCode: 'AQ',
    threeLetterCode: 'ATA',
    threeDigitCode: '010',
  },
  {
    name: 'Antigua and Barbuda',
    twoLetterCode: 'AG',
    threeLetterCode: 'ATG',
    threeDigitCode: '028',
  },
  {
    name: 'Argentina',
    twoLetterCode: 'AR',
    threeLetterCode: 'ARG',
    threeDigitCode: '032',
  },
  {
    name: 'Armenia',
    twoLetterCode: 'AM',
    threeLetterCode: 'ARM',
    threeDigitCode: '051',
  },
  {
    name: 'Aruba',
    twoLetterCode: 'AW',
    threeLetterCode: 'ABW',
    threeDigitCode: '533',
  },
  {
    name: 'Australia',
    twoLetterCode: 'AU',
    threeLetterCode: 'AUS',
    threeDigitCode: '036',
  },
  {
    name: 'Austria',
    twoLetterCode: 'AT',
    threeLetterCode: 'AUT',
    threeDigitCode: '040',
  },
  {
    name: 'Azerbaijan',
    twoLetterCode: 'AZ',
    threeLetterCode: 'AZE',
    threeDigitCode: '031',
  },
  {
    name: 'Bahamas',
    twoLetterCode: 'BS',
    threeLetterCode: 'BHS',
    threeDigitCode: '044',
  },
  {
    name: 'Bahrain',
    twoLetterCode: 'BH',
    threeLetterCode: 'BHR',
    threeDigitCode: '048',
  },
  {
    name: 'Bangladesh',
    twoLetterCode: 'BD',
    threeLetterCode: 'BGD',
    threeDigitCode: '050',
  },
  {
    name: 'Barbados',
    twoLetterCode: 'BB',
    threeLetterCode: 'BRB',
    threeDigitCode: '052',
  },
  {
    name: 'Belarus',
    twoLetterCode: 'BY',
    threeLetterCode: 'BLR',
    threeDigitCode: '112',
  },
  {
    name: 'Belgium',
    twoLetterCode: 'BE',
    threeLetterCode: 'BEL',
    threeDigitCode: '056',
  },
  {
    name: 'Belize',
    twoLetterCode: 'BZ',
    threeLetterCode: 'BLZ',
    threeDigitCode: '084',
  },
  {
    name: 'Benin',
    twoLetterCode: 'BJ',
    threeLetterCode: 'BEN',
    threeDigitCode: '204',
  },
  {
    name: 'Bermuda',
    twoLetterCode: 'BM',
    threeLetterCode: 'BMU',
    threeDigitCode: '060',
  },
  {
    name: 'Bhutan',
    twoLetterCode: 'BT',
    threeLetterCode: 'BTN',
    threeDigitCode: '064',
  },
  {
    name: 'Bolivia',
    twoLetterCode: 'BO',
    threeLetterCode: 'BOL',
    threeDigitCode: '068',
  },
  {
    name: 'Bosnia and Herzegovina',
    twoLetterCode: 'BA',
    threeLetterCode: 'BIH',
    threeDigitCode: '070',
  },
  {
    name: 'Botswana',
    twoLetterCode: 'BW',
    threeLetterCode: 'BWA',
    threeDigitCode: '072',
  },
  {
    name: 'Bouvet Island',
    twoLetterCode: 'BV',
    threeLetterCode: 'BVT',
    threeDigitCode: '074',
  },
  {
    name: 'Brazil',
    twoLetterCode: 'BR',
    threeLetterCode: 'BRA',
    threeDigitCode: '076',
  },
  {
    name: 'British Virgin Islands',
    twoLetterCode: 'VG',
    threeLetterCode: 'VGB',
    threeDigitCode: '092',
  },
  {
    name: 'British Indian Ocean Territory',
    twoLetterCode: 'IO',
    threeLetterCode: 'IOT',
    threeDigitCode: '086',
  },
  {
    name: 'Brunei Darussalam',
    twoLetterCode: 'BN',
    threeLetterCode: 'BRN',
    threeDigitCode: '096',
  },
  {
    name: 'Bulgaria',
    twoLetterCode: 'BG',
    threeLetterCode: 'BGR',
    threeDigitCode: '100',
  },
  {
    name: 'Burkina Faso',
    twoLetterCode: 'BF',
    threeLetterCode: 'BFA',
    threeDigitCode: '854',
  },
  {
    name: 'Burundi',
    twoLetterCode: 'BI',
    threeLetterCode: 'BDI',
    threeDigitCode: '108',
  },
  {
    name: 'Cambodia',
    twoLetterCode: 'KH',
    threeLetterCode: 'KHM',
    threeDigitCode: '116',
  },
  {
    name: 'Cameroon',
    twoLetterCode: 'CM',
    threeLetterCode: 'CMR',
    threeDigitCode: '120',
  },
  {
    name: 'Canada ',
    twoLetterCode: 'CA',
    threeLetterCode: 'CAN',
    threeDigitCode: '124',
  },
  {
    name: 'Cape Verde',
    twoLetterCode: 'CV',
    threeLetterCode: 'CPV',
    threeDigitCode: '132',
  },
  {
    name: 'Cayman Islands ',
    twoLetterCode: 'KY',
    threeLetterCode: 'CYM',
    threeDigitCode: '136',
  },
  {
    name: 'Central African Republic',
    twoLetterCode: 'CF',
    threeLetterCode: 'CAF',
    threeDigitCode: '140',
  },
  {
    name: 'Chad',
    twoLetterCode: 'TD',
    threeLetterCode: 'TCD',
    threeDigitCode: '148',
  },
  {
    name: 'Chile',
    twoLetterCode: 'CL',
    threeLetterCode: 'CHL',
    threeDigitCode: '152',
  },
  {
    name: 'China',
    twoLetterCode: 'CN',
    threeLetterCode: 'CHN',
    threeDigitCode: '156',
  },
  {
    name: 'Hong Kong, SAR China',
    twoLetterCode: 'HK',
    threeLetterCode: 'HKG',
    threeDigitCode: '344',
  },
  {
    name: 'Macao, SAR China',
    twoLetterCode: 'MO',
    threeLetterCode: 'MAC',
    threeDigitCode: '446',
  },
  {
    name: 'Christmas Island',
    twoLetterCode: 'CX',
    threeLetterCode: 'CXR',
    threeDigitCode: '162',
  },
  {
    name: 'Cocos (Keeling) Islands',
    twoLetterCode: 'CC',
    threeLetterCode: 'CCK',
    threeDigitCode: '166',
  },
  {
    name: 'Colombia',
    twoLetterCode: 'CO',
    threeLetterCode: 'COL',
    threeDigitCode: '170',
  },
  {
    name: 'Comoros',
    twoLetterCode: 'KM',
    threeLetterCode: 'COM',
    threeDigitCode: '174',
  },
  {
    name: 'Congo (Brazzaville) ',
    twoLetterCode: 'CG',
    threeLetterCode: 'COG',
    threeDigitCode: '178',
  },
  {
    name: 'Congo, (Kinshasa)',
    twoLetterCode: 'CD',
    threeLetterCode: 'COD',
    threeDigitCode: '180',
  },
  {
    name: 'Cook Islands ',
    twoLetterCode: 'CK',
    threeLetterCode: 'COK',
    threeDigitCode: '184',
  },
  {
    name: 'Costa Rica',
    twoLetterCode: 'CR',
    threeLetterCode: 'CRI',
    threeDigitCode: '188',
  },
  {
    name: "Côte d'Ivoire",
    twoLetterCode: 'CI',
    threeLetterCode: 'CIV',
    threeDigitCode: '384',
  },
  {
    name: 'Croatia',
    twoLetterCode: 'HR',
    threeLetterCode: 'HRV',
    threeDigitCode: '191',
  },
  {
    name: 'Cuba',
    twoLetterCode: 'CU',
    threeLetterCode: 'CUB',
    threeDigitCode: '192',
  },
  {
    name: 'Cyprus',
    twoLetterCode: 'CY',
    threeLetterCode: 'CYP',
    threeDigitCode: '196',
  },
  {
    name: 'Czech Republic',
    twoLetterCode: 'CZ',
    threeLetterCode: 'CZE',
    threeDigitCode: '203',
  },
  {
    name: 'Denmark',
    twoLetterCode: 'DK',
    threeLetterCode: 'DNK',
    threeDigitCode: '208',
  },
  {
    name: 'Djibouti',
    twoLetterCode: 'DJ',
    threeLetterCode: 'DJI',
    threeDigitCode: '262',
  },
  {
    name: 'Dominica',
    twoLetterCode: 'DM',
    threeLetterCode: 'DMA',
    threeDigitCode: '212',
  },
  {
    name: 'Dominican Republic',
    twoLetterCode: 'DO',
    threeLetterCode: 'DOM',
    threeDigitCode: '214',
  },
  {
    name: 'Ecuador',
    twoLetterCode: 'EC',
    threeLetterCode: 'ECU',
    threeDigitCode: '218',
  },
  {
    name: 'Egypt',
    twoLetterCode: 'EG',
    threeLetterCode: 'EGY',
    threeDigitCode: '818',
  },
  {
    name: 'El Salvador',
    twoLetterCode: 'SV',
    threeLetterCode: 'SLV',
    threeDigitCode: '222',
  },
  {
    name: 'Equatorial Guinea',
    twoLetterCode: 'GQ',
    threeLetterCode: 'GNQ',
    threeDigitCode: '226',
  },
  {
    name: 'Eritrea',
    twoLetterCode: 'ER',
    threeLetterCode: 'ERI',
    threeDigitCode: '232',
  },
  {
    name: 'Estonia',
    twoLetterCode: 'EE',
    threeLetterCode: 'EST',
    threeDigitCode: '233',
  },
  {
    name: 'Ethiopia',
    twoLetterCode: 'ET',
    threeLetterCode: 'ETH',
    threeDigitCode: '231',
  },
  {
    name: 'Falkland Islands (Malvinas) ',
    twoLetterCode: 'FK',
    threeLetterCode: 'FLK',
    threeDigitCode: '238',
  },
  {
    name: 'Faroe Islands',
    twoLetterCode: 'FO',
    threeLetterCode: 'FRO',
    threeDigitCode: '234',
  },
  {
    name: 'Fiji',
    twoLetterCode: 'FJ',
    threeLetterCode: 'FJI',
    threeDigitCode: '242',
  },
  {
    name: 'Finland',
    twoLetterCode: 'FI',
    threeLetterCode: 'FIN',
    threeDigitCode: '246',
  },
  {
    name: 'France',
    twoLetterCode: 'FR',
    threeLetterCode: 'FRA',
    threeDigitCode: '250',
  },
  {
    name: 'French Guiana',
    twoLetterCode: 'GF',
    threeLetterCode: 'GUF',
    threeDigitCode: '254',
  },
  {
    name: 'French Polynesia',
    twoLetterCode: 'PF',
    threeLetterCode: 'PYF',
    threeDigitCode: '258',
  },
  {
    name: 'French Southern Territories ',
    twoLetterCode: 'TF',
    threeLetterCode: 'ATF',
    threeDigitCode: '260',
  },
  {
    name: 'Gabon',
    twoLetterCode: 'GA',
    threeLetterCode: 'GAB',
    threeDigitCode: '266',
  },
  {
    name: 'Gambia',
    twoLetterCode: 'GM',
    threeLetterCode: 'GMB',
    threeDigitCode: '270',
  },
  {
    name: 'Georgia',
    twoLetterCode: 'GE',
    threeLetterCode: 'GEO',
    threeDigitCode: '268',
  },
  {
    name: 'Germany ',
    twoLetterCode: 'DE',
    threeLetterCode: 'DEU',
    threeDigitCode: '276',
  },
  {
    name: 'Ghana',
    twoLetterCode: 'GH',
    threeLetterCode: 'GHA',
    threeDigitCode: '288',
  },
  {
    name: 'Gibraltar ',
    twoLetterCode: 'GI',
    threeLetterCode: 'GIB',
    threeDigitCode: '292',
  },
  {
    name: 'Greece',
    twoLetterCode: 'GR',
    threeLetterCode: 'GRC',
    threeDigitCode: '300',
  },
  {
    name: 'Greenland',
    twoLetterCode: 'GL',
    threeLetterCode: 'GRL',
    threeDigitCode: '304',
  },
  {
    name: 'Grenada',
    twoLetterCode: 'GD',
    threeLetterCode: 'GRD',
    threeDigitCode: '308',
  },
  {
    name: 'Guadeloupe',
    twoLetterCode: 'GP',
    threeLetterCode: 'GLP',
    threeDigitCode: '312',
  },
  {
    name: 'Guam',
    twoLetterCode: 'GU',
    threeLetterCode: 'GUM',
    threeDigitCode: '316',
  },
  {
    name: 'Guatemala',
    twoLetterCode: 'GT',
    threeLetterCode: 'GTM',
    threeDigitCode: '320',
  },
  {
    name: 'Guernsey',
    twoLetterCode: 'GG',
    threeLetterCode: 'GGY',
    threeDigitCode: '831',
  },
  {
    name: 'Guinea',
    twoLetterCode: 'GN',
    threeLetterCode: 'GIN',
    threeDigitCode: '324',
  },
  {
    name: 'Guinea-Bissau',
    twoLetterCode: 'GW',
    threeLetterCode: 'GNB',
    threeDigitCode: '624',
  },
  {
    name: 'Guyana',
    twoLetterCode: 'GY',
    threeLetterCode: 'GUY',
    threeDigitCode: '328',
  },
  {
    name: 'Haiti',
    twoLetterCode: 'HT',
    threeLetterCode: 'HTI',
    threeDigitCode: '332',
  },
  {
    name: 'Heard and Mcdonald Islands',
    twoLetterCode: 'HM',
    threeLetterCode: 'HMD',
    threeDigitCode: '334',
  },
  {
    name: 'Holy See (Vatican City State)',
    twoLetterCode: 'VA',
    threeLetterCode: 'VAT',
    threeDigitCode: '336',
  },
  {
    name: 'Honduras',
    twoLetterCode: 'HN',
    threeLetterCode: 'HND',
    threeDigitCode: '340',
  },
  {
    name: 'Hungary',
    twoLetterCode: 'HU',
    threeLetterCode: 'HUN',
    threeDigitCode: '348',
  },
  {
    name: 'Iceland',
    twoLetterCode: 'IS',
    threeLetterCode: 'ISL',
    threeDigitCode: '352',
  },
  {
    name: 'India',
    twoLetterCode: 'IN',
    threeLetterCode: 'IND',
    threeDigitCode: '356',
  },
  {
    name: 'Indonesia',
    twoLetterCode: 'ID',
    threeLetterCode: 'IDN',
    threeDigitCode: '360',
  },
  {
    name: 'Iran, Islamic Republic of',
    twoLetterCode: 'IR',
    threeLetterCode: 'IRN',
    threeDigitCode: '364',
  },
  {
    name: 'Iraq',
    twoLetterCode: 'IQ',
    threeLetterCode: 'IRQ',
    threeDigitCode: '368',
  },
  {
    name: 'Ireland',
    twoLetterCode: 'IE',
    threeLetterCode: 'IRL',
    threeDigitCode: '372',
  },
  {
    name: 'Isle of Man ',
    twoLetterCode: 'IM',
    threeLetterCode: 'IMN',
    threeDigitCode: '833',
  },
  {
    name: 'Israel ',
    twoLetterCode: 'IL',
    threeLetterCode: 'ISR',
    threeDigitCode: '376',
  },
  {
    name: 'Italy ',
    twoLetterCode: 'IT',
    threeLetterCode: 'ITA',
    threeDigitCode: '380',
  },
  {
    name: 'Jamaica',
    twoLetterCode: 'JM',
    threeLetterCode: 'JAM',
    threeDigitCode: '388',
  },
  {
    name: 'Japan',
    twoLetterCode: 'JP',
    threeLetterCode: 'JPN',
    threeDigitCode: '392',
  },
  {
    name: 'Jersey',
    twoLetterCode: 'JE',
    threeLetterCode: 'JEY',
    threeDigitCode: '832',
  },
  {
    name: 'Jordan',
    twoLetterCode: 'JO',
    threeLetterCode: 'JOR',
    threeDigitCode: '400',
  },
  {
    name: 'Kazakhstan',
    twoLetterCode: 'KZ',
    threeLetterCode: 'KAZ',
    threeDigitCode: '398',
  },
  {
    name: 'Kenya',
    twoLetterCode: 'KE',
    threeLetterCode: 'KEN',
    threeDigitCode: '404',
  },
  {
    name: 'Kiribati',
    twoLetterCode: 'KI',
    threeLetterCode: 'KIR',
    threeDigitCode: '296',
  },
  {
    name: 'Korea (North)',
    twoLetterCode: 'KP',
    threeLetterCode: 'PRK',
    threeDigitCode: '408',
  },
  {
    name: 'Korea (South)',
    twoLetterCode: 'KR',
    threeLetterCode: 'KOR',
    threeDigitCode: '410',
  },
  {
    name: 'Kuwait',
    twoLetterCode: 'KW',
    threeLetterCode: 'KWT',
    threeDigitCode: '414',
  },
  {
    name: 'Kyrgyzstan',
    twoLetterCode: 'KG',
    threeLetterCode: 'KGZ',
    threeDigitCode: '417',
  },
  {
    name: 'Lao PDR',
    twoLetterCode: 'LA',
    threeLetterCode: 'LAO',
    threeDigitCode: '418',
  },
  {
    name: 'Latvia',
    twoLetterCode: 'LV',
    threeLetterCode: 'LVA',
    threeDigitCode: '428',
  },
  {
    name: 'Lebanon',
    twoLetterCode: 'LB',
    threeLetterCode: 'LBN',
    threeDigitCode: '422',
  },
  {
    name: 'Lesotho',
    twoLetterCode: 'LS',
    threeLetterCode: 'LSO',
    threeDigitCode: '426',
  },
  {
    name: 'Liberia',
    twoLetterCode: 'LR',
    threeLetterCode: 'LBR',
    threeDigitCode: '430',
  },
  {
    name: 'Libya',
    twoLetterCode: 'LY',
    threeLetterCode: 'LBY',
    threeDigitCode: '434',
  },
  {
    name: 'Liechtenstein',
    twoLetterCode: 'LI',
    threeLetterCode: 'LIE',
    threeDigitCode: '438',
  },
  {
    name: 'Lithuania',
    twoLetterCode: 'LT',
    threeLetterCode: 'LTU',
    threeDigitCode: '440',
  },
  {
    name: 'Luxembourg',
    twoLetterCode: 'LU',
    threeLetterCode: 'LUX',
    threeDigitCode: '442',
  },
  {
    name: 'Macedonia, Republic of',
    twoLetterCode: 'MK',
    threeLetterCode: 'MKD',
    threeDigitCode: '807',
  },
  {
    name: 'Madagascar',
    twoLetterCode: 'MG',
    threeLetterCode: 'MDG',
    threeDigitCode: '450',
  },
  {
    name: 'Malawi',
    twoLetterCode: 'MW',
    threeLetterCode: 'MWI',
    threeDigitCode: '454',
  },
  {
    name: 'Malaysia',
    twoLetterCode: 'MY',
    threeLetterCode: 'MYS',
    threeDigitCode: '458',
  },
  {
    name: 'Maldives',
    twoLetterCode: 'MV',
    threeLetterCode: 'MDV',
    threeDigitCode: '462',
  },
  {
    name: 'Mali',
    twoLetterCode: 'ML',
    threeLetterCode: 'MLI',
    threeDigitCode: '466',
  },
  {
    name: 'Malta',
    twoLetterCode: 'MT',
    threeLetterCode: 'MLT',
    threeDigitCode: '470',
  },
  {
    name: 'Marshall Islands',
    twoLetterCode: 'MH',
    threeLetterCode: 'MHL',
    threeDigitCode: '584',
  },
  {
    name: 'Martinique',
    twoLetterCode: 'MQ',
    threeLetterCode: 'MTQ',
    threeDigitCode: '474',
  },
  {
    name: 'Mauritania',
    twoLetterCode: 'MR',
    threeLetterCode: 'MRT',
    threeDigitCode: '478',
  },
  {
    name: 'Mauritius',
    twoLetterCode: 'MU',
    threeLetterCode: 'MUS',
    threeDigitCode: '480',
  },
  {
    name: 'Mayotte',
    twoLetterCode: 'YT',
    threeLetterCode: 'MYT',
    threeDigitCode: '175',
  },
  {
    name: 'Mexico',
    twoLetterCode: 'MX',
    threeLetterCode: 'MEX',
    threeDigitCode: '484',
  },
  {
    name: 'Micronesia, Federated States of',
    twoLetterCode: 'FM',
    threeLetterCode: 'FSM',
    threeDigitCode: '583',
  },
  {
    name: 'Moldova',
    twoLetterCode: 'MD',
    threeLetterCode: 'MDA',
    threeDigitCode: '498',
  },
  {
    name: 'Monaco',
    twoLetterCode: 'MC',
    threeLetterCode: 'MCO',
    threeDigitCode: '492',
  },
  {
    name: 'Mongolia',
    twoLetterCode: 'MN',
    threeLetterCode: 'MNG',
    threeDigitCode: '496',
  },
  {
    name: 'Montenegro',
    twoLetterCode: 'ME',
    threeLetterCode: 'MNE',
    threeDigitCode: '499',
  },
  {
    name: 'Montserrat',
    twoLetterCode: 'MS',
    threeLetterCode: 'MSR',
    threeDigitCode: '500',
  },
  {
    name: 'Morocco',
    twoLetterCode: 'MA',
    threeLetterCode: 'MAR',
    threeDigitCode: '504',
  },
  {
    name: 'Mozambique',
    twoLetterCode: 'MZ',
    threeLetterCode: 'MOZ',
    threeDigitCode: '508',
  },
  {
    name: 'Myanmar',
    twoLetterCode: 'MM',
    threeLetterCode: 'MMR',
    threeDigitCode: '104',
  },
  {
    name: 'Namibia',
    twoLetterCode: 'NA',
    threeLetterCode: 'NAM',
    threeDigitCode: '516',
  },
  {
    name: 'Nauru',
    twoLetterCode: 'NR',
    threeLetterCode: 'NRU',
    threeDigitCode: '520',
  },
  {
    name: 'Nepal',
    twoLetterCode: 'NP',
    threeLetterCode: 'NPL',
    threeDigitCode: '524',
  },
  {
    name: 'Netherlands',
    twoLetterCode: 'NL',
    threeLetterCode: 'NLD',
    threeDigitCode: '528',
  },
  {
    name: 'Netherlands Antilles',
    twoLetterCode: 'AN',
    threeLetterCode: 'ANT',
    threeDigitCode: '530',
  },
  {
    name: 'New Caledonia',
    twoLetterCode: 'NC',
    threeLetterCode: 'NCL',
    threeDigitCode: '540',
  },
  {
    name: 'New Zealand',
    twoLetterCode: 'NZ',
    threeLetterCode: 'NZL',
    threeDigitCode: '554',
  },
  {
    name: 'Nicaragua',
    twoLetterCode: 'NI',
    threeLetterCode: 'NIC',
    threeDigitCode: '558',
  },
  {
    name: 'Niger',
    twoLetterCode: 'NE',
    threeLetterCode: 'NER',
    threeDigitCode: '562',
  },
  {
    name: 'Nigeria',
    twoLetterCode: 'NG',
    threeLetterCode: 'NGA',
    threeDigitCode: '566',
  },
  {
    name: 'Niue ',
    twoLetterCode: 'NU',
    threeLetterCode: 'NIU',
    threeDigitCode: '570',
  },
  {
    name: 'Norfolk Island',
    twoLetterCode: 'NF',
    threeLetterCode: 'NFK',
    threeDigitCode: '574',
  },
  {
    name: 'Northern Mariana Islands',
    twoLetterCode: 'MP',
    threeLetterCode: 'MNP',
    threeDigitCode: '580',
  },
  {
    name: 'Norway',
    twoLetterCode: 'NO',
    threeLetterCode: 'NOR',
    threeDigitCode: '578',
  },
  {
    name: 'Oman',
    twoLetterCode: 'OM',
    threeLetterCode: 'OMN',
    threeDigitCode: '512',
  },
  {
    name: 'Pakistan',
    twoLetterCode: 'PK',
    threeLetterCode: 'PAK',
    threeDigitCode: '586',
  },
  {
    name: 'Palau',
    twoLetterCode: 'PW',
    threeLetterCode: 'PLW',
    threeDigitCode: '585',
  },
  {
    name: 'Palestinian Territory',
    twoLetterCode: 'PS',
    threeLetterCode: 'PSE',
    threeDigitCode: '275',
  },
  {
    name: 'Panama',
    twoLetterCode: 'PA',
    threeLetterCode: 'PAN',
    threeDigitCode: '591',
  },
  {
    name: 'Papua New Guinea',
    twoLetterCode: 'PG',
    threeLetterCode: 'PNG',
    threeDigitCode: '598',
  },
  {
    name: 'Paraguay',
    twoLetterCode: 'PY',
    threeLetterCode: 'PRY',
    threeDigitCode: '600',
  },
  {
    name: 'Peru',
    twoLetterCode: 'PE',
    threeLetterCode: 'PER',
    threeDigitCode: '604',
  },
  {
    name: 'Philippines',
    twoLetterCode: 'PH',
    threeLetterCode: 'PHL',
    threeDigitCode: '608',
  },
  {
    name: 'Pitcairn ',
    twoLetterCode: 'PN',
    threeLetterCode: 'PCN',
    threeDigitCode: '612',
  },
  {
    name: 'Poland',
    twoLetterCode: 'PL',
    threeLetterCode: 'POL',
    threeDigitCode: '616',
  },
  {
    name: 'Portugal',
    twoLetterCode: 'PT',
    threeLetterCode: 'PRT',
    threeDigitCode: '620',
  },
  {
    name: 'Puerto Rico',
    twoLetterCode: 'PR',
    threeLetterCode: 'PRI',
    threeDigitCode: '630',
  },
  {
    name: 'Qatar',
    twoLetterCode: 'QA',
    threeLetterCode: 'QAT',
    threeDigitCode: '634',
  },
  {
    name: 'Réunion',
    twoLetterCode: 'RE',
    threeLetterCode: 'REU',
    threeDigitCode: '638',
  },
  {
    name: 'Romania',
    twoLetterCode: 'RO',
    threeLetterCode: 'ROU',
    threeDigitCode: '642',
  },
  {
    name: 'Russian Federation ',
    twoLetterCode: 'RU',
    threeLetterCode: 'RUS',
    threeDigitCode: '643',
  },
  {
    name: 'Rwanda',
    twoLetterCode: 'RW',
    threeLetterCode: 'RWA',
    threeDigitCode: '646',
  },
  {
    name: 'Saint-Barthélemy',
    twoLetterCode: 'BL',
    threeLetterCode: 'BLM',
    threeDigitCode: '652',
  },
  {
    name: 'Saint Helena ',
    twoLetterCode: 'SH',
    threeLetterCode: 'SHN',
    threeDigitCode: '654',
  },
  {
    name: 'Saint Kitts and Nevis',
    twoLetterCode: 'KN',
    threeLetterCode: 'KNA',
    threeDigitCode: '659',
  },
  {
    name: 'Saint Lucia',
    twoLetterCode: 'LC',
    threeLetterCode: 'LCA',
    threeDigitCode: '662',
  },
  {
    name: ' Saint-Martin (French part)',
    twoLetterCode: 'MF',
    threeLetterCode: 'MAF',
    threeDigitCode: '663',
  },
  {
    name: 'Saint Pierre and Miquelon ',
    twoLetterCode: 'PM',
    threeLetterCode: 'SPM',
    threeDigitCode: '666',
  },
  {
    name: 'Saint Vincent and Grenadines',
    twoLetterCode: 'VC',
    threeLetterCode: 'VCT',
    threeDigitCode: '670',
  },
  {
    name: 'Samoa',
    twoLetterCode: 'WS',
    threeLetterCode: 'WSM',
    threeDigitCode: '882',
  },
  {
    name: 'San Marino',
    twoLetterCode: 'SM',
    threeLetterCode: 'SMR',
    threeDigitCode: '674',
  },
  {
    name: 'Sao Tome and Principe',
    twoLetterCode: 'ST',
    threeLetterCode: 'STP',
    threeDigitCode: '678',
  },
  {
    name: 'Saudi Arabia',
    twoLetterCode: 'SA',
    threeLetterCode: 'SAU',
    threeDigitCode: '682',
  },
  {
    name: 'Senegal',
    twoLetterCode: 'SN',
    threeLetterCode: 'SEN',
    threeDigitCode: '686',
  },
  {
    name: 'Serbia',
    twoLetterCode: 'RS',
    threeLetterCode: 'SRB',
    threeDigitCode: '688',
  },
  {
    name: 'Seychelles',
    twoLetterCode: 'SC',
    threeLetterCode: 'SYC',
    threeDigitCode: '690',
  },
  {
    name: 'Sierra Leone',
    twoLetterCode: 'SL',
    threeLetterCode: 'SLE',
    threeDigitCode: '694',
  },
  {
    name: 'Singapore',
    twoLetterCode: 'SG',
    threeLetterCode: 'SGP',
    threeDigitCode: '702',
  },
  {
    name: 'Slovakia',
    twoLetterCode: 'SK',
    threeLetterCode: 'SVK',
    threeDigitCode: '703',
  },
  {
    name: 'Slovenia',
    twoLetterCode: 'SI',
    threeLetterCode: 'SVN',
    threeDigitCode: '705',
  },
  {
    name: 'Solomon Islands',
    twoLetterCode: 'SB',
    threeLetterCode: 'SLB',
    threeDigitCode: '090',
  },
  {
    name: 'Somalia',
    twoLetterCode: 'SO',
    threeLetterCode: 'SOM',
    threeDigitCode: '706',
  },
  {
    name: 'South Africa',
    twoLetterCode: 'ZA',
    threeLetterCode: 'ZAF',
    threeDigitCode: '710',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    twoLetterCode: 'GS',
    threeLetterCode: 'SGS',
    threeDigitCode: '239',
  },
  {
    name: 'South Sudan',
    twoLetterCode: 'SS',
    threeLetterCode: 'SSD',
    threeDigitCode: '728',
  },
  {
    name: 'Spain',
    twoLetterCode: 'ES',
    threeLetterCode: 'ESP',
    threeDigitCode: '724',
  },
  {
    name: 'Sri Lanka',
    twoLetterCode: 'LK',
    threeLetterCode: 'LKA',
    threeDigitCode: '144',
  },
  {
    name: 'Sudan',
    twoLetterCode: 'SD',
    threeLetterCode: 'SDN',
    threeDigitCode: '736',
  },
  {
    name: 'Suriname',
    twoLetterCode: 'SR',
    threeLetterCode: 'SUR',
    threeDigitCode: '740',
  },
  {
    name: 'Svalbard and Jan Mayen Islands ',
    twoLetterCode: 'SJ',
    threeLetterCode: 'SJM',
    threeDigitCode: '744',
  },
  {
    name: 'Swaziland',
    twoLetterCode: 'SZ',
    threeLetterCode: 'SWZ',
    threeDigitCode: '748',
  },
  {
    name: 'Sweden',
    twoLetterCode: 'SE',
    threeLetterCode: 'SWE',
    threeDigitCode: '752',
  },
  {
    name: 'Switzerland',
    twoLetterCode: 'CH',
    threeLetterCode: 'CHE',
    threeDigitCode: '756',
  },
  {
    name: 'Syrian Arab Republic (Syria)',
    twoLetterCode: 'SY',
    threeLetterCode: 'SYR',
    threeDigitCode: '760',
  },
  {
    name: 'Taiwan, Republic of China ',
    twoLetterCode: 'TW',
    threeLetterCode: 'TWN',
    threeDigitCode: '158',
  },
  {
    name: 'Tajikistan',
    twoLetterCode: 'TJ',
    threeLetterCode: 'TJK',
    threeDigitCode: '762',
  },
  {
    name: 'Tanzania, United Republic of ',
    twoLetterCode: 'TZ',
    threeLetterCode: 'TZA',
    threeDigitCode: '834',
  },
  {
    name: 'Thailand',
    twoLetterCode: 'TH',
    threeLetterCode: 'THA',
    threeDigitCode: '764',
  },
  {
    name: 'Timor-Leste',
    twoLetterCode: 'TL',
    threeLetterCode: 'TLS',
    threeDigitCode: '626',
  },
  {
    name: 'Togo',
    twoLetterCode: 'TG',
    threeLetterCode: 'TGO',
    threeDigitCode: '768',
  },
  {
    name: 'Tokelau ',
    twoLetterCode: 'TK',
    threeLetterCode: 'TKL',
    threeDigitCode: '772',
  },
  {
    name: 'Tonga',
    twoLetterCode: 'TO',
    threeLetterCode: 'TON',
    threeDigitCode: '776',
  },
  {
    name: 'Trinidad and Tobago',
    twoLetterCode: 'TT',
    threeLetterCode: 'TTO',
    threeDigitCode: '780',
  },
  {
    name: 'Tunisia',
    twoLetterCode: 'TN',
    threeLetterCode: 'TUN',
    threeDigitCode: '788',
  },
  {
    name: 'Turkey',
    twoLetterCode: 'TR',
    threeLetterCode: 'TUR',
    threeDigitCode: '792',
  },
  {
    name: 'Turkmenistan',
    twoLetterCode: 'TM',
    threeLetterCode: 'TKM',
    threeDigitCode: '795',
  },
  {
    name: 'Turks and Caicos Islands ',
    twoLetterCode: 'TC',
    threeLetterCode: 'TCA',
    threeDigitCode: '796',
  },
  {
    name: 'Tuvalu',
    twoLetterCode: 'TV',
    threeLetterCode: 'TUV',
    threeDigitCode: '798',
  },
  {
    name: 'Uganda',
    twoLetterCode: 'UG',
    threeLetterCode: 'UGA',
    threeDigitCode: '800',
  },
  {
    name: 'Ukraine',
    twoLetterCode: 'UA',
    threeLetterCode: 'UKR',
    threeDigitCode: '804',
  },
  {
    name: 'United Arab Emirates',
    twoLetterCode: 'AE',
    threeLetterCode: 'ARE',
    threeDigitCode: '784',
  },
  {
    name: 'United Kingdom',
    twoLetterCode: 'GB',
    threeLetterCode: 'GBR',
    threeDigitCode: '826',
  },
  {
    name: 'United States of America',
    twoLetterCode: 'US',
    threeLetterCode: 'USA',
    threeDigitCode: '840',
  },
  {
    name: 'US Minor Outlying Islands ',
    twoLetterCode: 'UM',
    threeLetterCode: 'UMI',
    threeDigitCode: '581',
  },
  {
    name: 'Uruguay',
    twoLetterCode: 'UY',
    threeLetterCode: 'URY',
    threeDigitCode: '858',
  },
  {
    name: 'Uzbekistan',
    twoLetterCode: 'UZ',
    threeLetterCode: 'UZB',
    threeDigitCode: '860',
  },
  {
    name: 'Vanuatu',
    twoLetterCode: 'VU',
    threeLetterCode: 'VUT',
    threeDigitCode: '548',
  },
  {
    name: 'Venezuela (Bolivarian Republic)',
    twoLetterCode: 'VE',
    threeLetterCode: 'VEN',
    threeDigitCode: '862',
  },
  {
    name: 'Viet Nam',
    twoLetterCode: 'VN',
    threeLetterCode: 'VNM',
    threeDigitCode: '704',
  },
  {
    name: 'Virgin Islands, US',
    twoLetterCode: 'VI',
    threeLetterCode: 'VIR',
    threeDigitCode: '850',
  },
  {
    name: 'Wallis and Futuna Islands ',
    twoLetterCode: 'WF',
    threeLetterCode: 'WLF',
    threeDigitCode: '876',
  },
  {
    name: 'Western Sahara ',
    twoLetterCode: 'EH',
    threeLetterCode: 'ESH',
    threeDigitCode: '732',
  },
  {
    name: 'Yemen',
    twoLetterCode: 'YE',
    threeLetterCode: 'YEM',
    threeDigitCode: '887',
  },
  {
    name: 'Zambia',
    twoLetterCode: 'ZM',
    threeLetterCode: 'ZMB',
    threeDigitCode: '894',
  },
  {
    name: 'Zimbabwe',
    twoLetterCode: 'ZW',
    threeLetterCode: 'ZWE',
    threeDigitCode: '716',
  },
];
