export const streetNames: string[] = [
  'Miami',
  'Boston',
  'Dallas',
  'Houston',
  'Kitty Hawk',
  'Duck',
  'Nags Head',
  'Manteo',
  'Wanchese',
  'Coinjock',
  'Kissington',
  'Lillington',
  'Denver',
  'Colorado Springs',
  'Fort Collins',
  'Fayetteville',
  'Asheville',
  'Asheborro',
  'Dunn',
  'Benson',
  'Houston',
  'Dallas',
  'Boston',
  'Baltimore',
  'Virginia Beach',
  'Norfolk',
  'Suffolk',
  'Klonton',
  'Farmville',
  'Radnor',
  'Lynchburg',
  'Boone',
  'Greensboro',
  'Greenville',
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Columbus',
  'Indianapolis',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'El Paso',
  'Washington',
  'Boston',
  'Detroit',
  'Nashville',
  'Memphis',
  'Portland',
  'Oklahoma City',
  'Las Vegas',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Mesa',
  'Kansas City',
  'Atlanta',
  'Long Beach',
  'Colorado Springs',
  'Raleigh',
  'Miami',
  'Virginia Beach',
  'Omaha',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Arlington',
  'New Orleans',
  'Wichita',
  'Cleveland',
  'Tampa',
  'Bakersfield',
  'Aurora',
  'Honolulu',
  'Anaheim',
  'San Juan',
  'Santa Ana',
  'Corpus Christi',
  'Riverside',
  'Lexington',
  'St. Louis',
  'Stockton',
  'Pittsburgh',
  'Saint Paul',
  'Cincinnati',
  'Anchorage',
  'Henderson',
  'Greensboro',
  'Plano',
  'Newark',
  'Lincoln',
  'Toledo',
  'Orlando',
  'Chula Vista',
  'Irvine',
  'Fort Wayne',
  'Jersey City',
  'Durham',
  'St. Petersburg',
  'Laredo',
  'Buffalo',
  'Madison',
  'Lubbock',
  'Chandler',
  'Scottsdale',
  'Glendale',
  'Reno',
  'Norfolk',
  'Winston–Salem',
  'North',
  'Irving',
  'Chesapeake',
  'Gilbert',
  'Hialeah',
  'Garland',
  'Fremont',
  'Baton Rouge',
  'Richmond',
  'Boise',
  'San Bernardino',
  'Spokane',
  'Des Moines',
  'Modesto',
  'Birmingham',
  'Tacoma',
  'Fontana',
  'Rochester',
  'Oxnard',
  'Moreno Valley',
  'Fayetteville',
  'Aurora',
  'Glendale',
  'Yonkers',
  'Huntington',
  'Montgomery',
  'Amarillo',
  'Little Rock',
  'Akron',
  'Columbus',
  'Augusta',
  'Grand Rapids',
  'Shreveport',
  'Salt Lake City',
  'Huntsville',
  'Mobile',
  'Tallahassee',
  'Grand Prairie',
  'Overland Park',
  'Knoxville',
  'Port St. Lucie',
  'Worcester',
  'Bayamón',
  'Brownsville',
  'Tempe',
  'Santa Clarita',
  'Newport News',
  'Cape Coral',
  'Providence',
  'Fort Lauderdale',
  'Chattanooga',
  'Rancho Cucamonga',
  'Oceanside',
  'Santa Rosa',
  'Garden Grove',
  'Vancouver',
  'Sioux Falls',
  'Ontario',
  'McKinney',
  'Elk Grove',
  'Jackson',
  'Pembroke Pines',
  'Salem',
  'Springfield',
  'Corona',
  'Eugene',
  'Fort Collins',
  'Peoria',
  'Frisco',
  'Cary',
  'Lancaster',
  'Hayward',
  'Carolina',
  'Palmdale',
  'Salinas',
  'Alexandria',
  'Lakewood',
  'Springfield',
  'Pasadena',
  'Sunnyvale',
  'Macon',
  'Pomona',
  'Hollywood',
  'Kansas City',
  'Escondido',
  'Clarksville',
  'Joliet',
  'Rockford',
  'Torrance',
  'Naperville',
  'Paterson',
  'Savannah',
  'Bridgeport',
  'Ponce',
  'Mesquite',
  'Killeen',
  'Syracuse',
  'McAllen',
  'Pasadena',
  'Bellevue',
  'Fullerton',
  'Orange',
  'Dayton',
  'Miramar',
  'Thornton',
  'West Valley City',
  'Olathe',
  'Hampton',
  'Warren',
  'Midland',
  'Waco',
  'Charleston',
  'Columbia',
  'Denton',
  'Carrollton',
  'Surprise',
  'Roseville',
  'Sterling Heights',
  'Caguas',
  'Murfreesboro',
  'Gainesville',
  'Cedar Rapids',
  'Visalia',
  'Coral Springs',
  'New Haven',
  'Stamford',
  'Thousand Oaks',
  'Concord',
  'Elizabeth',
  'Lafayette',
  'Kent',
  'Topeka',
  'Simi Valley',
  'Santa Clara',
  'Athens',
  'Hartford',
  'Victorville',
  'Abilene',
  'Norman',
  'Vallejo',
  'Berkeley',
  'Round Rock',
  'Ann Arbor',
  'Fargo',
  'Columbia',
  'Allentown',
  'Evansville',
  'Beaumont',
  'Odessa',
  'Wilmington',
  'Arvada',
  'Independence',
  'Provo',
  'Lansing',
  'El Monte',
  'Springfield',
  'Fairfield',
  'Clearwater',
  'Peoria',
  'Rochester',
  'Carlsbad',
  'Westminster',
  'West Jordan',
  'Pearland',
  'Richardson',
  'Downey',
  'Miami Gardens',
  'Temecul',
  'Costa Mesa',
  'College Station',
  'Elgin',
  'Murrieta',
  'Gresham',
  'High Point',
  'Antioch',
  'Inglewood',
  'Cambridge',
  'Lowell',
  'Manchester',
  'Billings',
  'Pueblo',
  'Palm Bay',
  'Centennial',
  'Richmond',
  'Ventura',
  'Pompano Beach',
  'North Charleston',
  'Everett',
  'Waterbury',
  'West Palm Beach',
  'Boulder',
  'West Covina',
  'Broken Arrow',
  'Clovis',
  'Daly City',
  'Lakeland',
  'Santa Maria',
  'Norwalk',
  'Sandy Springs',
  'Hillsboro',
  'Green Bay',
  'Tyler',
  'Wichita Falls',
  'Lewisville',
  'Burbank',
  'Greeley',
  'San Mateo',
  'El Cajon',
  'Jurupa Valley',
  'Rialto',
  'Davenport',
  'League City',
  'Edison',
  'Davie',
  'Las Cruces',
  'South Bend',
  'Vista',
  'Woodbridge',
  'Renton',
  'Lakewood',
  'San Angelo',
  'Clinton',
  'Catache',
  'Guadalupe',
  'Phatthalung',
  'Santo Estevao',
  'Xitou',
  'Okinawa',
  'Liwale',
  'Goroka',
  'Jacura',
  'Longmen',
  'Proletar',
  'Luofang',
  'Melun',
  'Mirsini',
  'Pitanga',
  'Pasadena',
  'Pidhue',
  'Carriedo',
  'Benhao',
  'Barra',
  'Markham',
  'La Breita',
  'Rantis',
  'Bertoua',
  'Dagang',
  'Ponong',
  'Chahe',
  'Nantes',
  'Pitea',
  'Ozu',
  'Jingling',
  'Strasbourg',
  'Frontier',
  'Butterworth',
  'Duhu',
  'Cemara',
  'Stockholm',
  'Kradinski',
  'Guane',
  'La Palma',
  'La Cruz',
  'Valbo',
  'Lazurne',
  'Bontang',
  'Westerfield',
  'Westerton',
  'Easterton',
  'Easterfield',
  'Westworld',
  'Eastworld',
  'Eastville',
  'Genova',
  'Luxi',
  'Luna',
  'Parry Sound',
  'Southern Shores',
  'Chicahauk',
  'Collington',
  'Breadville',
  'Padderson',
  'Paddertonville',
  'West End',
  'West Elm',
  'West Birch',
  'West Cedar',
  'Cedar',
  'Poplar',
  'South Poplar',
  'Midspring',
  'Midwinter',
  'Midsummer',
  'Nightsdream',
  'Clear Lake',
  'Whispy Falls',
  'Sandy Shores',
  'Charleston',
  'Charlottesville',
  'Randerton',
  'Louisville',
  'Williamsburg',
  'Southerland',
  'Northerland',
  'Northland',
  'Southland',
  'North Park',
  'South Park',
  'West Park',
  'East Park',
  'East Lake',
  'Bird',
  'Wingbird',
  'Calgary',
  'Mustang',
  'Ford',
  'Cadillac',
  'Condor',
  'Lazy',
  'Rapid',
  'Trenton',
  'Greenway',
  'Validity',
  'Greenston',
  'Gruyere',
  'Hustler',
  'Green',
  'Bloomfield',
  'Bloomer',
  'Bloomberg',
  'Blooms',
  'Brightbloom',
  'Yellowbloom',
  'Blue',
  'Red',
  'Yellow',
  'Black',
  'Brown',
  'Beverly',
  'Blue',
  'Hancock',
  'Childress',
  'Albatross',
  'Random',
  'Rover',
  'Silver',
  'Gold',
  'Goldsmith',
  'Blacksmith',
  'Ringer',
  'Sparrow',
  'Bluebird',
  'Robin',
  'Rocky',
  'First',
  'Second',
  'Third',
  'Fourth',
  'Fifth',
  'Sixth',
  'Seventh',
  'Eighth',
  'Ninth',
  'Tenth',
  'Eleventh',
  'Twelfth',
  'Thirteenth',
  'Fourteenth',
  'Fifteenth',
  'Sixteenth',
  'Seventeenth',
  'Rider',
  'Mansion',
  'Root',
  'Bigfoot',
  'Lavender',
  'Dandelion',
  'Spring',
  'Silver Spring',
  'Hot Spring',
  'Rainbow',
  'Kitten',
  'Donkey',
  'Horseshoe',
  'Seashore',
  'Seashell',
  'Piper',
  'Plover',
  'Rose',
  'Trenton',
  'Treehouse',
  'Javascript',
  'React',
  'Node',
  'Java',
  'Mocha',
  'Kronos',
  'Chaitea',
  'Chai',
  'Latte',
  'Machiatto',
  'Macho Man',
  'Wonder Woman',
  'Wonder',
  'Tech Support',
  'Technology',
  'Franklin',
  'Roosevelt',
  'Morrison',
  'Granville',
  'Rosemary',
  'Thyme',
  'Licorice',
  'Candy',
  'Candyland',
  'Clue',
  'Monopoly',
  'Darkhorse',
  'Fetty Wap',
  'Womper',
  'Bass',
  'Pike',
  'Boardwalk',
  'Ocean',
  'Wave',
  'Swell',
  'Avalanche',
  'Ruby',
  'Rails',
  'Railway',
  'Yard',
  'Cypress',
  'Glassdoor',
  'Brickhouse',
  'Saphire',
  'Magenta',
  'Opal',
  'Emerald',
  'Cook',
  'Howe',
  'Estes',
  'Colorado',
  'Sandpiper',
  'Willow',
  'Willowtree',
  'Oak',
  'Pine',
  'Birch',
  'Mahogany',
  'Cherrywood',
  'Balsa',
  'Aberg',
  'Acker',
  'Alper',
  'Algoma',
  'Almo',
  'Alpine',
  'American',
  'China',
  'Arnoth',
  'Amoth',
  'Anderson',
  'Anhalt',
  'Annamark',
  'Anniversary',
  'Anthes',
  'Anzinger',
  'Arapahoe',
  'Tuckahoe',
  'Arizona',
  'Arkansas',
  'Armistice',
  'Arrowood',
  'Artisan',
  'Atwood',
  'Autumn Leaf',
  'Badeau',
  'Banding',
  'Barby',
  'Barnett',
  'Barnard',
  'Bartillon',
  'Bashford',
  'Basil',
  'Plant',
  'Planter',
  'Bay',
  'Bayside',
  'Becker',
  'Beilfuss',
  'Bellgrove',
  'Blackbird',
  'Blaine',
  'Bleriot',
  'Byrd',
  'Eckner',
  'Bluestem',
  'Greenthumb',
  'Bobcat',
  'Bowman',
  'Bowie',
  'Bodie',
  'Boyd',
  'Brentwood',
  'Briar Crest',
  'Brickson Park',
  'Buell',
  'Bull',
  'Bullhorn',
  'Buena Vista',
  'Buhler',
  'Bultman',
  'Bunting',
  'Burning Wood',
  'Burrows',
  'Butterfield',
  'Butternut',
  'Callang',
  'Calypso',
  'Morpheus',
  'Neo',
  'Cambridge',
  'Homer',
  'Illiad',
  'Odyssey',
  'Troy',
  'Canary',
  'Cardinal',
  'Carey',
  'Carioca',
  'Carpenter',
  'Cascade',
  'Center',
  'Charing Cross',
  'Cherokee',
  'Chinook',
  'Chive',
  'Claremont',
  'Mont Verde',
  'Clemons',
  'Clove',
  'Clover',
  'Coleman',
  'Columbus',
  'Comanche',
  'Commercial',
  'Continental',
  'Coolidge',
  'Corbean',
  'Corry',
  'Quarry',
  'Carribean',
  'Corscot',
  'Cottonwood',
  'Crescent Oaks',
  'Crest Line',
  'Crowley',
  'Del Mar',
  'Delaware',
  'Delladonna',
  'Division',
  'Dixon',
  'Doe Crossing',
  'Dunning',
  'Eastwood',
  'Blackwood',
  'Bluewood',
  'Redwood',
  'Eggendart',
  'Elk',
  'Express',
  'Fair Oaks',
  'Fairfield',
  'Farmco',
  'Fieldstone',
  'Florence',
  'Fremont',
  'Glendale',
  'Glenwood',
  'Wade',
  'Golden Leaf',
  'Golf',
  'Golf Course',
  'Goodland',
  'Badland',
  'Graceland',
  'Granby',
  'Grover',
  'Green Ridge',
  'Blue Ridge',
  'Blue Hills',
  'Rolling Hills',
  'Hallows',
  'Hanover',
  'Hanson',
  'Harbort',
  'Hooker',
  'Hovde',
  'Homewood',
  'Iowa',
  'Dadford',
  'Kipling',
  'Mineral',
  'Killdeer',
  'Laurel',
  'Lakewood',
  'La Follette',
  'Lighthouse Bay',
  'Lindbergh',
  'Lotheville',
  'Lunder',
  'Lyons',
  'Mallard Cove',
  'Mandrake',
  'Goose',
  'Liza',
  'Hyrule',
  'Duku Tree',
  'Windy Alley',
  'Whispy Tree',
  'Whispy Flower',
  'Whispy Wood',
  'Burntwood',
  'Burnt Toast',
  'Buttered Bun',
  'Maple Wood',
  'Manufacturers',
  'Marinars Cove',
  'Pirates Cove',
  'Maryland',
  'Mayfield',
  'Memorial',
  'Carnival',
  'Festival',
  'Party',
  'Mockingbird',
  'Songbird',
  'Morrow',
  'Monument',
  'Hadano',
  'Northview',
  'Southview',
  'New Castle',
  'New Eagle',
  'New School',
  'New Flower',
  'Mayflower',
  'Little Rock',
  'Boyscout',
  'Girlscout',
  'Big Rock',
  'Stone Slope',
  'New England',
  'Pilgrim',
  'New Land',
  'New Shore',
  'Shoresands',
  'Big Wave',
  'Voodoo',
  'Ranger',
  'Goku',
  'Gecko',
  'Lizard',
  'Little Dragon',
  'Namekagon',
  'Nova',
  'Old Gate',
  'Rusty Bench',
  'Wooden Handle',
  'Oxford',
  'Tableau',
  'Pearson',
  'Pawling',
  'Pepper Wood',
  'Pleasure Pond',
  'Prairie Rose',
  'Prairieview',
  'Apprentice',
  'Magician',
  'Wizard',
  'Red Cloud',
  'Black Cloud',
  'Grey Sky',
  'Red Sky',
  'Blue Sky',
  'Ridgeview',
  'Ridgeport',
  'Riverside',
  'Dockside',
  'Dockport',
  'Rockefeller',
  'Roxbury',
  'School',
  'Springview',
  'Winterview',
  'Summerview',
  'Stone Corner',
  'Summit',
  'Summer Ridge',
  'Stonebrook',
  'Sunbrook',
  'Brookside',
  'Babbling Brook',
  'Crystal Creek',
  'Shallow Creek',
  'Sycamore',
  'Talisman',
  'Talmadge',
  'Trailsway',
  'Towne',
  'Twin Pines',
  'Whispering Pines',
  'Valley Edge',
  'Union',
  'Village',
  'Vermont',
  'Village Green',
  'Warbler',
  'Warrior',
  'Wayridge',
  'Wayport',
  'Waywood',
  'Weed',
  'Weedway',
  'Weedly',
  'Weebly',
  'Weber',
  'Webber',
  'Webston',
  'Weeping Birch',
  'Waxwing',
  'Deep Basin',
  'Shallow River',
  'Shallow',
  'Deep Pit',
];
