export const titles: string[] = [
  'CEO',
  'Chief Executive Officer',
  'COO',
  'Chief Operations Officer',
  'CFO',
  'Chief Financial Officer',
  'CTO',
  'Chief Technical Officer',
  'Account Manager',
  'SDR',
  'Sales Development Representative',
  'Marketing Representative',
  'Software Engineer',
  'Account Executive',
  'Database Administrator',
  'Technical Support Specialist',
  'Chief Marketing Officer',
  'VP Engineering',
  'VP Sales',
  'VP Marketing',
  'Operations Manager',
  'Accounting Manager',
];
