name: Deploy lambda to AWS

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      lambdaFunctionName:
        required: true
        type: string
      extraFiles:
        required: false
        type: string
        default: ''
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-lambda:
    name: Deploy lambda to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo app=${{ inputs.appName }} lambda=${{ inputs.lambdaFunctionName }} extraFiles=${{ inputs.extraFiles }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Retrieve deployment bundle
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Debug
        run: pwd && ls -R .

      - name: Zip lambda for deployment
        run: zip -r ${{ inputs.appName }}.zip ${{ inputs.appName }} ${{ inputs.extraFiles }}

      - name: Debug
        run: pwd && ls -R .

      - name: Debug root and scripts directory
        run: |
          ls -l
          ls -l scripts || true

      - name: Upload lambda function code to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws lambda update-function-code --function-name "${{ inputs.lambdaFunctionName }}" --zip-file "fileb://${{ github.workspace }}/${{ inputs.appName }}.zip"
