name: Deploy to development environment

on:
  push:
    branches: [main]

# env:
#   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#   TEST_COGNITO_USERNAME: ${{ secrets.TEST_COGNITO_USERNAME }}
#   TEST_COGNITO_PASSWORD: ${{ secrets.TEST_COGNITO_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{ steps.affected-apps.outputs.AFFECTED_APPS }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'main'

      - name: Build all apps
        run: yarn nx run-many --target=build --all --configuration=test

      - name: Debug dist folder
        run: |
          pwd
          ls dist || true
          ls dist/apps || true

      - name: Persist deployment bundle
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ github.workspace }}/dist/apps/

      - name: Set affected apps output
        id: affected-apps
        run: |
          if [ -d dist/apps ]; then
            FOUND_APPS=$(find dist/apps -type d -maxdepth 1 -mindepth 1 | cut -d '/' -f 3)
            APPS=$(echo $FOUND_APPS | tr ' ' ',')
            echo "AFFECTED_APPS=$APPS" >> $GITHUB_OUTPUT
          else
            echo "AFFECTED_APPS=" >> $GITHUB_OUTPUT
          fi

  deploy-charlesmbrady-web:
    needs: build
    if: contains(needs.build.outputs.affected_apps, 'charlesmbrady-web')
    uses: ./.github/workflows/s3_deploy_from_build.yml
    with:
      appName: 'charlesmbrady-web'
      bucketName: 'charlesmbrady-test-website-content'
      s3SyncOptions: '--delete'
      appType: 'react'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-mockdat-web:
    needs: build
    if: contains(needs.build.outputs.affected_apps, 'mockdat-web')
    uses: ./.github/workflows/s3_deploy_from_build.yml
    with:
      appName: 'mockdat-web'
      bucketName: 'mockdat-test-website-content'
      s3SyncOptions: '--delete'
      appType: 'react'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-apps:
    needs: build
    if: contains(needs.build.outputs.affected_apps, 'apps')
    uses: ./.github/workflows/s3_deploy_from_build.yml
    with:
      appName: 'apps'
      bucketName: 'apps-test-website-content'
      s3SyncOptions: '--delete'
      appType: 'react'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-api-services:
    needs: build
    if: contains(needs.build.outputs.affected_apps, 'api-services')
    uses: ./.github/workflows/lambda_deploy_from_build.yml
    with:
      appName: 'api-services'
      lambdaFunctionName: 'charlesmbrady_api_services_Test'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
