name: Deploy to production environment (tag)

# When we push a tag, we want to build and deploy the app
on:
  push:
    tags:
      - 'charlesmbrady-web-*.*.*'
      - 'mockdat-web-*.*.*'
      - 'labs-*.*.*'
      - 'api-services-*.*.*'

jobs:
  set-app-name:
    runs-on: ubuntu-latest
    outputs:
      app_name: ${{ steps.set-app-name.outputs.APP_NAME }}
      tag_name: ${{ steps.set-app-name.outputs.TAG_NAME }}
    steps:
      - name: Set app name from tag
        id: set-app-name
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          APP_NAME=$(echo "$TAG_NAME" | sed -E 's/-[0-9]+\.[0-9]+\.[0-9]+$//')
          echo "APP_NAME=$APP_NAME" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: set-app-name
    runs-on: ubuntu-latest
    if: |
      needs.set-app-name.outputs.app_name == 'charlesmbrady-web' ||
      needs.set-app-name.outputs.app_name == 'mockdat-web' ||
      needs.set-app-name.outputs.app_name == 'labs' ||
      needs.set-app-name.outputs.app_name == 'api-services'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn nx run ${{ needs.set-app-name.outputs.app_name }}:build

      - name: Debug dist folder
        run: |
          ls -l dist || true
          ls -l dist/apps || true

      - name: Persist deployment bundle
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ needs.set-app-name.outputs.app_name }}
          path: ${{ github.workspace }}/dist/apps/${{ needs.set-app-name.outputs.app_name }}

      - name: Deploy to S3
        if: |
          needs.set-app-name.outputs.app_name == 'charlesmbrady-web' ||
          needs.set-app-name.outputs.app_name == 'mockdat-web' ||
          needs.set-app-name.outputs.app_name == 'labs'
        run: |
          if [ "${{ needs.set-app-name.outputs.app_name }}" = "charlesmbrady-web" ]; then
            ./scripts/deploy_app.sh --env production charlesmbrady-web charlesmbrady-production-website-content --type react
          elif [ "${{ needs.set-app-name.outputs.app_name }}" = "mockdat-web" ]; then
            ./scripts/deploy_app.sh --env production mockdat-web mockdat-production-website-content --type react
          elif [ "${{ needs.set-app-name.outputs.app_name }}" = "labs" ]; then
            ./scripts/deploy_app.sh --env production labs labs-production-website-content --type react
          fi

      - name: Deploy Lambda
        if: needs.set-app-name.outputs.app_name == 'api-services'
        run: ./scripts/deploy_lambda.sh --env production --nx-project-name api-services --lambda-name api-services-prod
